name: MSBuild

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

env:
  SOLUTION_FILE_PATH: .\ArchipelagoMod.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        build_config: ["Release", "Debug"]

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'

    - uses: microsoft/setup-msbuild@v3
    
    - uses: actions/cache@v5
      with:
        path: |
          ./Dependencies/APCpp
        key: ${{ runner.os }}-APCpp-${{ matrix.build_config }}-${{ hashFiles('**/APCpp/CMakeLists.txt', '**/APCpp/*.c', '**/APCpp/*.h') }}

    - name: Configure APCpp
      working-directory: ./Dependencies/APCpp
      run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_config }} -S . -B out

    - name: Build APCpp
      working-directory: ./Dependencies/APCpp
      run: cmake --build out --config ${{ matrix.build_config }}
      
    # - name: Artifact APCpp
      # uses: actions/upload-artifact@v6
      # with:
        # name: artifact-apcpp-${{ matrix.build_config }}
        # path: .\Dependencies\APCpp\out\${{ matrix.build_config }}\*

    - name: Build Archipelago
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{ matrix.build_config }} ${{env.SOLUTION_FILE_PATH}}

    - shell: cmd
      run: move .\x64\${{ matrix.build_config }}\ArchipelagoMod.dll .\dist\ArchipelagoMod\

    - shell: cmd
      run: move .\Dependencies\APCpp\out\${{ matrix.build_config }}\APCpp.dll .\dist\ArchipelagoMod\
      
    - shell: cmd
      run: move .\LICENSE.TXT .\dist\ArchipelagoMod\

    - name: Artifact
      uses: actions/upload-artifact@v6
      with:
        name: artifact-ArchipelagoMod-${{ matrix.build_config }}
        path: .\dist\*
        compression-level: 9 # not my compute.