name: MSBuild

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

env:
  SOLUTION_FILE_PATH: .\ArchipelagoMod.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        build_config: ["Release", "Debug"]

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'

    - uses: microsoft/setup-msbuild@v3
    
    - name: Restore APCpp build cache
      id: apcpp-cache
      uses: actions/cache/restore@v5
      with:
        path: |
          ./Dependencies/APCpp
        key: ${{ runner.os }}-APCpp-${{ matrix.build_config }}-${{ hashFiles('**/APCpp/CMakeLists.txt', '**/APCpp/*.c', '**/APCpp/*.h') }}

    - name: Configure APCpp
      working-directory: ./Dependencies/APCpp
      run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_config }} -S . -B out

    - name: Save APCpp build cache
      if: >
        github.event_name != 'pull_request' &&
        steps.apcpp-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: |
          ./Dependencies/APCpp
        key: ${{ steps.apcpp-cache.outputs.cache-primary-key }}

    - name: Build APCpp
      working-directory: ./Dependencies/APCpp
      run: cmake --build out --config ${{ matrix.build_config }}
      
    # - name: Artifact APCpp
      # uses: actions/upload-artifact@v6
      # with:
        # name: artifact-apcpp-${{ matrix.build_config }}
        # path: .\Dependencies\APCpp\out\${{ matrix.build_config }}\*

    - name: Build Archipelago
      run: msbuild /m /p:Configuration=${{ matrix.build_config }} ${{env.SOLUTION_FILE_PATH}}

    - shell: cmd
      run: move .\x64\${{ matrix.build_config }}\ArchipelagoMod.dll .\dist\ArchipelagoMod\

    - shell: cmd
      run: move .\Dependencies\APCpp\out\${{ matrix.build_config }}\APCpp.dll .\dist\ArchipelagoMod\
      
    - shell: cmd
      run: move .\LICENSE.TXT .\dist\ArchipelagoMod\

    - name: Artifact
      uses: actions/upload-artifact@v6
      with:
        name: artifact-ArchipelagoMod-${{ matrix.build_config }}
        path: .\dist\*
        compression-level: 9 # not my compute.
        
    # APCpp doesn't supply a PDB for Release by default and cmd move doesn't have error suppression
    - name: Flatten PDBs
      shell: pwsh
      run: |
        mkdir pdb
        move .\x64\${{ matrix.build_config }}\ArchipelagoMod.pdb .\pdb
        move .\Dependencies\APCpp\out\${{ matrix.build_config }}\APCpp.pdb .\pdb -ErrorAction SilentlyContinue

    - name: Artifact PDBs
      uses: actions/upload-artifact@v6
      with:
        name: artifact-ArchipelagoMod-${{ matrix.build_config }}-PDB
        path: .\pdb\
        compression-level:

  post:
    needs: build
    steps: 
      - name: Summarize
        shell: bash
        run: |
          echo "Debug builds require Visual Studio installed with the \"Desktop Development with C++\" workload." >> $GITHUB_STEP_SUMMARY