name: MSBuild

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

env:
  SOLUTION_FILE_PATH: .\ArchipelagoMod.sln
  BUILD_CONFIGURATION: Release # Debug is required for proper APCpp linking until it's built as Release, also helps stacktraces I guess.

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'

    - uses: microsoft/setup-msbuild@v3
    
    - uses: actions/cache@v5
      with:
        path: |
          ./Dependencies/APCpp
        key: ${{ runner.os }}-APCpp-${{ hashFiles('**/APCpp/CMakeLists.txt', '**/APCpp/*.c', '**/APCpp/*.h') }}

    - name: Configure APCpp
      working-directory: ./Dependencies/APCpp
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_CONFIGURATION}} -S . -B out

    - name: Build APCpp
      working-directory: ./Dependencies/APCpp
      run: cmake --build out --config ${{env.BUILD_CONFIGURATION}}
      
    # - name: Artifact APCpp
      # uses: actions/upload-artifact@v6
      # with:
        # name: artifact-apcpp-${{env.BUILD_CONFIGURATION}}
        # path: .\Dependencies\APCpp\out\${{env.BUILD_CONFIGURATION}}\*

    - name: Build Archipelago
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - shell: cmd
      run: move .\x64\Release\ArchipelagoMod.dll .\dist\ArchipelagoMod\

    - shell: cmd
      run: move .\Dependencies\APCpp\out\Release\APCpp.dll .\dist\ArchipelagoMod\
      
    - shell: cmd
      run: move .\LICENSE.TXT .\dist\ArchipelagoMod\

    - name: Artifact
      uses: actions/upload-artifact@v6
      with:
        name: artifact-ArchipelagoMod-${{env.BUILD_CONFIGURATION}}
        path: .\dist\*
        compression-level: 9 # not my compute.